# Generated by Django 5.1.1 on 2025-05-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('user_registration', 'User Registration'), ('patient_added', 'Patient Added'), ('provider_added', 'Provider Added'), ('record_created', 'Record Created'), ('record_updated', 'Record Updated'), ('record_accessed', 'Record Accessed'), ('appointment_scheduled', 'Appointment Scheduled'), ('appointment_cancelled', 'Appointment Cancelled'), ('prescription_added', 'Prescription Added'), ('prescription_removed', 'Prescription Removed'), ('access_granted', 'Access Granted'), ('access_revoked', 'Access Revoked')], max_length=50)),
                ('event_details', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('related_wallet_address', models.CharField(max_length=42)),
            ],
        ),
    ]
