# Generated by Django 5.1.1 on 2025-05-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('user_registration', 'User Registration'), ('patient_added', 'Patient Added'), ('provider_added', 'Provider Added'), ('record_created', 'Record Created'), ('record_updated', 'Record Updated'), ('record_accessed', 'Record Accessed'), ('appointment_scheduled', 'Appointment Scheduled'), ('appointment_cancelled', 'Appointment Cancelled'), ('prescription_added', 'Prescription Added'), ('prescription_removed', 'Prescription Removed'), ('access_granted', 'Access Granted'), ('access_revoked', 'Access Revoked'), ('note_added', 'Note Added'), ('note_removed', 'Note Removed')], max_length=50),
        ),
    ]
