# Generated by Django 5.1.1 on 2025-05-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='related_patient_wallet_address',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
    ]
